version: '3.3'
services:
  k6:
    image: grafana/k6@sha256:cf680d4f4251220743021bc6ae2b246679f47a986bd7468f3f25d2013f327495
    container_name: k6
    volumes:
      - '${PWD}/src:/scripts'
    environment:
      - OCP_APIM_SUBSCRIPTION_KEY=${ocp_apim_subscription_key}
      - VARS=${env}.environment.json
      - TEST_TYPE=/scripts/test-types/${type}.json
      - K6_OUT=influxdb=http://nginx:8086/${db_name}
    command: run /scripts/${script}.js
    depends_on:
      - nginx

  nginx:
    image: nginx@sha256:fb39280b7b9eba5727c884a3c7810002e69e8f961cc373b89c92f14961d903a0
    container_name: nginx
    volumes:
      - '${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf'
    environment:
      - ENVIRONMENT=${env}
    ports:
      - "8086:8086"
      - "80:80"

