# azure-pipelines.yml
trigger: none

parameters:
  - name: "ENVIRONMENT"
    displayName: "Environment"
    type: string
    values:
      - "dev"
      - "uat"
    default: "uat"
  - name: "TEST_TYPE"
    displayName: "Test type"
    type: string
    values:
      - "load"
      - "smoke"
      - "soak"
      - "spike"
      - "stress"
      - "constant"
      - # TODO: add your values
    default: "constant"
  - name: "SCRIPT"
    displayName: "Script name"
    type: string
    values:
      - yourscriptname # TODO: add your script
variables:
  ${{ if eq(parameters['ENVIRONMENT'], 'dev') }}:
    poolImage: 'pagopa-dev-loadtest-linux'
    API_SUBSCRIPTION_KEY: $(DEV_API_SUBSCRIPTION_KEY)
  ${{ if eq(parameters['ENVIRONMENT'], 'uat') }}:
    poolImage: 'pagopa-uat-loadtest-linux'
    API_SUBSCRIPTION_KEY: $(UAT_API_SUBSCRIPTION_KEY)


pool:
  name: $(poolImage)

steps:
  - script: |
      cd ./performance-test/src
      docker pull grafana/k6
    displayName: Pull k6 image

    # TODO: add your env params
  - script: |
      cd ./performance-test
      sh ./run_performance_test.sh ${{ parameters.ENVIRONMENT }} ${{ parameters.TEST_TYPE }} ${{ parameters.SCRIPT }} afmcalculatork6 $(API_SUBSCRIPTION_KEY)
    displayName: Run k6 ${{ parameters.SCRIPT }} on ${{ parameters.ENVIRONMENT }}
