microservice-chart:
  namespace: "receipts"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: ghcr.io/pagopa/pagopa-receipt-pdf-service
    tag: "0.3.0"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 90
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  serviceMonitor:
    create: true
    endpoints:
      - interval: 10s #jmx-exporter
        targetPort: 12345
        path: /metrics
  ports:
    - 8080 #http
    - 12345 #jmx-exporter
  service:
    type: ClusterIP
    ports:
      - 8080 #http
      - 12345 #jmx-exporter
  ingress:
    create: true
    host: "weudev.receipts.internal.dev.platform.pagopa.it"
    path: /pagopa-receipt-pdf-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "0.25"
    limits:
      memory: "512Mi"
      cpu: "0.25"
  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "75"
  fileConfig: {}
  envConfig:
    APP_ENVIRONMENT: "dev"
    WEBSITE_SITE_NAME: 'pagopareceiptpdfservice' # required to show cloud role name in application insights
    APP_LOGGING_LEVEL: 'DEBUG'
    DEFAULT_LOGGING_LEVEL: 'INFO'
    COSMOS_RECEIPT_SERVICE_ENDPOINT: "https://pagopa-d-weu-receipts-ds-cosmos-account.documents.azure.com:443/"
    COSMOS_RECEIPT_DB_NAME: "db"
    COSMOS_RECEIPT_CONTAINER_NAME: "receipts"
    BLOB_STORAGE_ACCOUNT_ENDPOINT: "https://pagopadweureceiptsfnsa.blob.core.windows.net/"
    BLOB_STORAGE_CONTAINER_NAME: "pagopa-d-weu-receipts-azure-blob-receipt-st-attach"
    JAVA_TOOL_OPTIONS: "-javaagent:/deployments/jmx_prometheus_javaagent-0.19.0.jar=12345:/deployments/config.yaml -Xmx1024m -XX:+UseG1GC"
  envFieldRef:
  envSecret:
    # required
    APPLICATIONINSIGHTS_CONNECTION_STRING: 'ai-d-connection-string'
    COSMOS_RECEIPT_KEY: "cosmos-receipt-pkey"
    BLOB_STORAGE_CONN_STRING: "receipts-storage-account-connection-string"
  keyvault:
    name: "pagopa-d-receipts-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    create: true
    ingress:
      create: true
      canary:
        type: header
        headerName: X-Canary
        headerValue: canary
        weightPercent: 0
    service:
      create: true
    deployment:
      create: true
      image:
        repository: ghcr.io/pagopa/pagopa-receipt-pdf-service
        tag: "0.3.0"
        pullPolicy: Always
      envConfig: {}
      envSecret: {}
